# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{brains}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Lloyd"]
  s.date = %q{2009-11-17}
  s.default_executable = %q{brains}
  s.description = %q{Get some Brains!}
  s.email = %q{christopher.lloyd@gmail.com}
  s.executables = ["brains"]
  s.files = [
    "Rakefile",
     "VERSION",
     "bin/brains",
     "brains.gemspec",
     "lib/brains.rb",
     "lib/brains/cli.rb",
     "lib/brains/helpers.rb",
     "lib/brains/version.rb",
     "templates/brain.rb.erb",
     "templates/config.ru.erb"
  ]
  s.homepage = %q{http://github.com/chrislloyd/brains}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Get some Brains!}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

