begin
  require 'jeweler'
  Jeweler::Tasks.new do |gs|
    gs.name = "brains"
    gs.summary = "Get some Brains!"
    gs.description = gs.summary
    gs.homepage = "http://github.com/chrislloyd/brains"
    gs.author = "Chris Lloyd"
    gs.email = "christopher.lloyd@gmail.com"

    # gs.executables = 'brains'
    # gs.add_dependency 'pixii', '>= 0.1.6'
    # gs.add_dependency 'dnssd', '>= 1.3.1'
  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Install Jeweler to build gem"
end
