require 'rubygems'
require 'rake'

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = 'brains'
    # gem.summary = %Q{TODO: one-line summary of your gem}
    # gem.description = %Q{TODO: longer description of your gem}
    gem.email = 'christopher.lloyd@gmail.com'
    gem.homepage = 'http://github.com/chrislloyd/brains'
    gem.author = 'Chris Lloyd'

    gem.executable = 'brains'

    gem.add_development_dependency 'exemplor'

  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: sudo gem install jeweler"
end

task :test => :check_dependencies
